sudo: required
services:
    - docker
before_install:
    - docker build -t nesspll/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nesspll/react-test npm test

after_success:
    - docker build -t nesspll/multi-client ./client
    - docker build -t nesspll/multi-worker ./worker
    - docker build -t nesspll/multi-server ./server
    - docker build -t nesspll/multi-nginx ./nginx
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push nesspll/multi-client 
    - docker push nesspll/multi-worker 
    - docker push nesspll/multi-server 
    - docker push nesspll/multi-nginx 